#!/bin/sh

if [ $# != 1 ]; then
    echo >&2 "Usage: $0 bytes"
    exit 1
fi

# rinse and repeat
while true; do

    # delete the old key (if any)
    rm -f input.pub input.sec

    # use gpg to generate a new key (we better have LOADS of entropy available!)
    gpg --batch --gen-key <<- EOF
	%echo Generating a basic OpenPGP key
	Key-Type: RSA
	Key-Length: 4096
	Subkey-Type: RSA
	Subkey-Length: 1024
	Name-Real: this uid will be gone anyways
	Name-Email: x.y@z
	Expire-Date: 0
	%pubring input.pub
	%secring input.sec
	Passphrase: abc
	# Do a commit here, so that we can later print "done" :-)
	%commit
	%echo done
EOF
    gpg --keyring ./input.pub --export-secret-keys > ./input.sec
    # vanity~
    ./vanity input.pub input.sec 1262300400 $1 && break

done
